<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BILET</title>
</head>
<body>
<h1>Bilet</h1><hr>
<h4>Авторизация</h4>
<form action="/login" method="post">
  Почта: <input type="email" name="username"><br><br>
  Пароль: <input type="password" name="password"><br><br>
  <input type="submit"  value="вход"/>
</form>
<a href="/registration">Зарегистрироваться</a>
</body>
</html>

